"""add marketplace_discount to sale

Revision ID: 145c1900a03e
Revises: 8dcc7db9b094
Create Date: 2026-08-24 07:49:12.284182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145c1900a03e'
down_revision = '8dcc7db9b094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('marketplace_discount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'marketplace_discount')
    # ### end Alembic commands ###
