"""Add customer_price to sales

Revision ID: 8dcc7db9b094
Revises: 98f3202cf575
Create Date: 2026-08-23 21:20:51.689753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcc7db9b094'
down_revision = '98f3202cf575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    op.add_column('sales', sa.Column('customer_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'customer_price')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    # ### end Alembic commands ###
